### ISSUE TITLE
Incorrect Results

### ISSUE THREAD

**Issue by Erodotos** [iwpnd/piper#1]
Hello!

I was trying to check the validity of the results while using the provided geojson file for Berlin. In fact, here is my code below : 

```
func main() {
	p := []float64{52.50341777065819, 13.334090061514702}

	raw, err := ioutil.ReadFile("./testdata/berlin.geojson")
	if err != nil {
		panic("something went wrong")
	}

	var feature geojson.Feature
	err = json.Unmarshal(raw, &feature)
	if err != nil {
		panic("something went wrong")
	}

	polygon := feature.Geometry.Polygon

	pip := piper.Pip(p, polygon)
	fmt.Printf("Point in Polygon: %+v\n", pip)
}
```

The selected coordinates `52.50341777065819, 13.334090061514702` lie in Berlin (You can check using google maps). Nevertheless, the returned result is `false`, indicating that this point is not within Berlin.

Any ideas about this issue? Am I using piper properly?

**Comment by iwpnd** [comment]
Hi, it's the classic issue of coordinate order. It's []float64{longitude,latitude}. I'll add a note to the docs for the next person. :)

edit:
Added it!

Thanks for reporting 🙏🏻
